application:
  name: CCloud

server:
  host: 
  port: 80

logging:
  level: DEBUG
  file: /app/log/ccloud.log
  maxSize: 10
  maxAge: 30
  maxBackups: 5
  localTime: true
  compress: false

store:
  imagePath: /app/images/
  videoPath: /app/videos/

datasource:
  driverName: sqlite3
  config:
    dbPath: /app/db/ccloud.db

account:
  username: demo
  password: 12345678A
  
  