application:
  name: CCloud

server:
  host: localhost
  port: 8080

logging:
  level: DEBUG
  path: ccloud.log

ccloud:
  store:
    image: /app/images/
    video: /app/videos/
  datasource:
    driver:
    url: 
    user:
    password:
  
  