# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "feature-list-file" ]
  pull_request:
    branches: [ "main", "feature-list-file" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        ls -al
        go build 
    
    - name: archivement
      uses: actions/upload-artifact@v3
      with:
          name: dist
          path: |
            ccloud
